language: c
env:
  - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/
install:
  - curl www.rust-lang.org/rustup.sh | sudo bash
script:
  - rustc --version
  - cargo build -v
  - cargo test -v
os:
  - linux
